# Generated by Django 5.1.3 on 2024-11-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('indicatif', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('consentement', models.BooleanField(default=False)),
                ('step', models.CharField(max_length=50)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
